name: Update Site

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.ipynb"
      - "references.yml"
      - "**/*.md"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.svg"
      - "**/*.gif"
      - "**/*.pdf"

  workflow_dispatch: {}

jobs:
  site:
    uses: Academic-Codex/academic-codex.github.io/.github/workflows/build-site.yml@main
    with:
      execute: "false"
      template_repo: "Academic-Codex/academic-codex.github.io"
      template_ref: "main"
    permissions:
      contents: write
      pages: write
      id-token: write